= Auoscaling with Knative

In this exercise,  you’ll install (subscribe) Red Hat Openshift Serverless operator. Then, you’ll deploy a Quarkus application to test serverless autoscaling using Knative Pod Autoscaler (KPA) with a minimum of 0 pods, and scaling based on requests per second.

[#install]
== Install Prerequisites

=== Install Red Hat Openshift Serverless

1) Install Red Hat Openshift Serverless operator using the CLI or the https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-openshift-serverless.html#serverless-install-web-console_installing-openshift-serverless[Web Console].

====
Go to Operator Hub,  search Red Hat OpenShift Serverless, and install. Keep the default options, click on Install and wait until the installation finishes.
====

After that, install Knative Serving using the https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-knative-serving.html#serverless-install-serving-yaml_installing-knative-serving[CLI] or the https://docs.openshift.com/container-platform/4.6/serverless/installing_serverless/installing-knative-serving.html#serverless-install-serving-web-console_installing-knative-serving[Web Console].

====
Go to Openshift Serverless operator, select knative-serving project, and click on Install Knative Serving. Keep all the default values, and click on Install.
====

Check the installation finished properly.

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
$ oc get knativeserving.operator.knative.dev/knative-serving -n knative-serving --template='{{range .status.conditions}}{{printf "%s=%s\n" .type .status}}{{end}}'

DependenciesInstalled=True
DeploymentsAvailable=True
InstallSucceeded=True
Ready=True
VersionMigrationEligible=True
----

=== Kn Client 

Download the Kn client for Linux from https://storage.googleapis.com/knative-nightly/client/latest/kn-linux-amd64[here], and save it in any folder of your path (i.e. /usr/local/bin). Check your kn client is working properly, and enable autocompletion for your shell.

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
$ wget https://storage.googleapis.com/knative-nightly/client/latest/kn-linux-amd64
$ sudo mv kn-linux-amd64 /usr/local/bin/kn
$ sudo chmod +x /usr/local/bin/kn
$ source <(kn completion bash)
$ kn version
----

=== Java OpenJDK 11

Ensure you have installed `java-11-openjdk` and `java-11-openjdk-devel`, and `JAVA_HOME` env var is set.

----
$ sudo dnf install java-11-openjdk  java-11-openjdk-devel
$ java -version
$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-11.0.9.11-4.fc33.x86_64
----

=== Apache Maven 3.6.2 (or higher)

Ensure you have installed Apache Maven 3.6.2 or higher.

----
$ sudo dnf install maven
$ mvn -version
Apache Maven 3.6.3 (Red Hat 3.6.3-5)
Maven home: /usr/share/maven
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-4.fc33.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.13-200.fc33.x86_64", arch: "amd64", family: "unix"
----

[#quarkus]
== Build the Quarkus app

2) Download the Quarkus app source code to your computer. You can clone the repository `https://github.com/albertogd/rh-serverless.git` and go to `apps/knative/quarkus`. Create the project `quarkus-demo`, and compile with mvn the Quarkus application.

[source,bash,subs="+macros,+attributes"]
----
$ git clone https://github.com/albertogd/rh-serverless.git /tmp/rh-serverless
$ cd /tmp/rh-serverless/apps/knative/quarkus

$ oc new-project quarkus-demo
$ ./mvnw clean package -Dquarkus.kubernetes.deploy=true
----

[IMPORTANT]
====
If you use a different project name, change the project name in `src/main/resources/application.properties`

[source,bash]
----
quarkus.container-image.group=<project_name>
----
====

[NOTE]
====
This is a basic Quarkus application where the https://access.redhat.com/documentation/en-us/red_hat_build_of_quarkus/1.7/html/deploying_your_quarkus_applications_as_openshift_serverless_services/proc-deploy-serverless-quarkus-java-app-openshift-ext_deploy-quarkus-openshift-serverless[following steps] have already been done:

* Add the OpenShift extension to an existing project:
+
----
$ ./mvnw quarkus:add-extension -Dextensions="openshift"
----
+

*  Direct OpenShift to use the Open JDK 11 Red Hat Enterprise Linux 8 image. Added the following line to *application.properties*
+
----
quarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-11
----
+

* Direct OpenShift Serverless to pull your container image from the OpenShift internal registry. Added the following line to *application.properties*
+
----
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
----
+

* Enable the creation of deployment descriptors for Knative Serving. Added the following line to the *application.properties* file.
+
----
quarkus.kubernetes.deployment-target=knative
----
+

* Added the project so Quarkus can pull the image from the image registry. Added the following line to the *application.properties* file.
+
----
quarkus.container-image.group=quarkus-demo
----
+
====

Check the application works properly. Get the route, and make a curl request or browse:

[source,bash,subs="+macros,+attributes"]
----
$ oc get ksvc quarkus-app -o json | jq -r '.status.url'
$ curl $(oc get ksvc quarkus-app -o json | jq -r '.status.url')
----

[#native]
== Deploy the Quarkus application compiled to a Native Executable

3) Now you'll deploy the Quarkus application compileted to a native executable.

[NOTE]
====
These steps are based on https://access.redhat.com/documentation/en-us/red_hat_build_of_quarkus/1.7/html/deploying_your_quarkus_applications_on_red_hat_openshift_container_platform/con-deploying-quarkus-serverless[deploy a Quarkus application compiled to a native executable on Red Hat OpenShift Container Platform using OpenShift Serverless Knative Serving].
====

In the same repository, go to `apps/knative/quarkus-native`. Build a Linux executable:

[source,bash,subs="+macros,+attributes"]
----
$ ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman -Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-20-rhel8:20.1
----

Create the image `quarkus-native-app:v1` using the dockerfile `src/main/docker/Dockerfile.native`:

[source,bash,subs="+macros,+attributes"]
----
$ podman build -f src/main/docker/Dockerfile.native -t quarkus-native-app:v1 .
----

Expose Openshift registry using DefaultRoute:

[source,bash,subs="+macros,+attributes"]
----
$ oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
----

Log in Openshift with a user with permissions in project quarkus-demo and get the token.

[NOTE]
====
If you don't have a IdentityProvider, follow these steps:

[source,bash,subs="+macros,+attributes"]
----
$ htpasswd -c -B -b /tmp/htpasswd admin redhat
$ oc create secret generic htpass-secret --from-file=htpasswd=/tmp/htpasswd -n openshift-config
$ oc edit OAuth
----

In OAuth add:

[source,yaml,subs="+macros,+attributes"]
----
  identityProviders:
  - name: htpasswd 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
----

Wait a couple of minutes. After that, you shoule be able to log in with user `admin` and password `redhat`.

====

[source,bash,subs="+macros,+attributes"]
----
$ oc adm policy add-clusterrole-to-user cluster-admin admin
----

Push the container to Openshift registry:

[source,bash,subs="+macros,+attributes"]
----
$ podman login -u admin -p $(oc whoami -t) $(oc get route default-route -n openshift-image-registry -o json | jq -r '.spec.host')
$ skopeo copy containers-storage:localhost/quarkus-native-app:v1 docker://$(oc get route default-route -n openshift-image-registry -o json | jq -r '.spec.host')/quarkus-demo/quarkus-native-app:v1.0 --dest-tls-verify=false
----

Create the Knative Service `quarkus-native-app` using the Quarkus native image

[source,bash,subs="+macros,+attributes"]
----
$ kn service create quarkus-native-app --image $(oc get istag quarkus-native-app:v1 -o jsonpath='{.image.dockerImageReference}')  --revision-name quarkus-native-app-v1
----

Check the application works properly. Get the route, and make a curl request or browse:

[source,bash,subs="+macros,+attributes"]
----
$ oc get ksvc quarkus-native-app -o json | jq -r '.status.url'
$ curl $(oc get ksvc quarkus-native-app -o json | jq -r '.status.url')
----

[#java]
== Create a Java Spring Boot app

4) Now you'll build a Java Spring Boot application image using S2I, and you'll use that image to create a Knative Service. Import the image stream `openjdk18-openshift:1.1`, and use that image stream to build the application:

- *Name*: java-app
- *Repo*: https://github.com/albertogd/rh-serverless.git
- *Branch*: master
- *Path*: apps/knative/java
- *Image Stream*: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.1

[source,bash,subs="+macros,+attributes"]
----
$ oc import-image --confirm openjdk/openjdk18-openshift:1.1 --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.1
$ oc new-build --name java-app --image-stream openjdk18-openshift:1.1 https://github.com/albertogd/serverless-apps.git#serverless --context-dir=knative/java --to java-app:v1
----

Create the Knative Service `java-app`, and configure the revision-name as `java-app-v1`.

[source,bash,subs="+macros,+attributes"]
----
$ kn service create java-app --image $(oc get istag java-app:v1 -o jsonpath='{.image.dockerImageReference}')  --revision-name java-app-v1
----

Check the application works properly. Get the route, and make a curl request or browse:

[source,bash,subs="+macros,+attributes"]
----
$ oc get ksvc quarkus-app -o json | jq -r '.status.url'
$ curl $(oc get ksvc java-app -o json | jq -r '.status.url')
----

[#test]
== Test the applications

5) Make a request to each of you applications. How long does it take each answer?

[source,bash,subs="+macros,+attributes"]
----
$ time curl $(oc get ksvc quarkus-app -o json | jq -r '.status.url')
... 0,01s user 0,01s system 0% cpu 7,176 total

$ time curl $(oc get ksvc quarkus-native-app -o json | jq -r '.status.url')
...   0,01s user 0,01s system 0% cpu 3,839 total

$ time curl $(oc get ksvc java-app -o json | jq -r '.status.url')
... 0,01s user 0,01s system 0% cpu 10,191 total
----

====

* Quarkus native application takes 4 second
* Quarkus application takes around 7 seconds
* Java Spring Boot applicattion takes around 10 seconds

====

[#autoscale]
== Configure a Knative Service to autoscale

6) Configure the Knative Service `quarkus-app` for the application to  auto scales 1 replica each 5 requests per seconds (i.e. an application receiving 15 requests, should have 3 replicas). Use the following parameters:

* **Service**: quarkus-app 
* **Revision name**: quarkus-app-v1 
* **Scale**:
** Min: 0
** Max: 10
* **Autoscale parameters**:
** Metrics: rps
** Target: 5

[source,bash,subs="+macros,+attributes"]
----
$ kn service update quarkus-app --revision-name quarkus-app-v1 --scale 0..10 --annotation autoscaling.knative.dev/metric="rps" --annotation autoscaling.knative.dev/target="5"
----

The script https://raw.githubusercontent.com/albertogd/rh-serverless/master/apps/knative/scripts/create-replicas-quarkus-app.sh[create-replicas-quarkus-app.sh] generates the amount of requests needed so Knative autoscales the app to the replicas you want. Run create-replicas-quarkus-app.sh 2 to generate 2 replicas.

NOTE: You can also use https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64[hey] to generate concurrent request per second

[source,bash,subs="+macros,+attributes"]
----
$ wget https://raw.githubusercontent.com/albertogd/rh-serverless/master/apps/knative/scripts/create-replicas-quarkus-app.sh
$ chmod +x ./create-replicas-quarkus-app.sh
$ ./create-replicas-quarkus-app.sh 2
Current pod nº: 0
Current pod nº: 0
Current pod nº: 0
Current pod nº: 0
Current pod nº: 1
Current pod nº: 2
Current pod nº: 2
Current pod nº: 2
----

Do a single request and check the kpa. After one minute, check the kpa. What is the current status?

[source,bash,subs="+macros,+attributes"]
----
$ curl -s $(oc get ksvc quarkus-app -o json | jq -r '.status.url') >/dev/null

$ oc get kpa
NAME                     DESIREDSCALE   ACTUALSCALE   READY   REASON
quarkus-app-v1               1               1        True  

-- After 1 minute...

$ oc get kpa
NAME               DESIREDSCALE   ACTUALSCALE   READY   REASON
quarkus-app              0             1        False   NoTraffic

-- After some seconds...

$ oc get kpa
NAME               DESIREDSCALE   ACTUALSCALE   READY   REASON
quarkus-app             0              0        False   NoTraffic
----

====
After the request, the DESIREDSCALE is 1, and ACTUALSCALE is 0. After 7 seconds, both are 1. Between 60-90 seconds, DESIREDSCALE becomes 0. And after 90 seconds, ACTUALSCALE becomes 0. 
====
